---
title: "STATS331Final Q"
subtitle: "Checkpoint3 Choosing data"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
    number-sections: true
editor: visual
execute: 
  error: true
  echo: true
  message: false
  warning: false
---
```{r setup}
#| include: false
library(tidyverse)
```


## Dataset 

```{r}
Soldierdata <- read.csv("armed_forces_personnel_percent_of_labor_force.csv")
Murderdata <- read.csv("murder_per_100000_people.csv")
```

## Cleaning Data

```{r}
colnames(Soldierdata) <- gsub("^X", "", colnames(Soldierdata))
colnames(Murderdata) <- gsub("^X", "", colnames(Murderdata))

Soldierdata$country <- str_trim(Soldierdata$country)
Murderdata$country <- str_trim(Murderdata$country)

Soldierdata[is.na(Soldierdata)] <- 0
Murderdata[is.na(Murderdata)] <- 0

Soldierdata_long <- pivot_longer(Soldierdata, cols = -country, names_to = "year", values_to = "soldiers")
Murderdata_long <- pivot_longer(Murderdata, cols = -country, names_to = "year", values_to = "murder_rate")

FinalData <- full_join(Soldierdata_long, Murderdata_long, by = c("country", "year"))

FinalData
```

